import type {
  InstagramPost,
  InstagramProfile,
  BrandProfile,
  ContentSuggestion,
  NicheCompetitor,
  NicheTrend,
  AnalyticsData,
  CalendarEvent,
  PerformanceInsight,
} from "@/types/instagram";

/**
 * Demo data for the app to showcase all features
 * without requiring a live Instagram API connection.
 */

export const demoProfile: InstagramProfile = {
  id: "demo-user",
  username: "peptide_pro",
  fullName: "Peptide Pro",
  biography:
    "Science-backed peptide education & wellness tips. Helping you optimize health through peptide therapy. DM for collabs.",
  profilePicUrl: "",
  followers: 24500,
  following: 890,
  postsCount: 342,
  isVerified: false,
  category: "Health & Wellness",
  externalUrl: "https://peptidepro.com",
};

const basePosts: InstagramPost[] = [
  {
    id: "post-1",
    shortcode: "abc123",
    caption:
      "BPC-157: The healing peptide you need to know about. Studies show it accelerates wound healing, gut repair, and tissue regeneration.\n\nHere are 5 science-backed benefits:\n1. Gut healing\n2. Tendon repair\n3. Anti-inflammatory\n4. Neuroprotective\n5. Muscle recovery\n\nHave you tried BPC-157? Share your experience below!\n\n#peptides #bpc157 #biohacking #wellness #health #peptidetherapy #healing #guthealth",
    mediaType: "CAROUSEL",
    mediaUrl: "",
    timestamp: "2026-03-15T10:30:00Z",
    likes: 1250,
    comments: 89,
    engagementRate: 5.47,
    hashtags: ["#peptides", "#bpc157", "#biohacking", "#wellness", "#health", "#peptidetherapy", "#healing", "#guthealth"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-2",
    shortcode: "def456",
    caption:
      "Stop making this mistake with your peptide protocol.\n\nMost people don't realize that timing matters. Here's when to take the most common peptides for maximum results.\n\n#peptides #optimization #health #biohacking #wellness",
    mediaType: "VIDEO",
    mediaUrl: "",
    timestamp: "2026-03-12T14:00:00Z",
    likes: 2100,
    comments: 156,
    engagementRate: 9.21,
    hashtags: ["#peptides", "#optimization", "#health", "#biohacking", "#wellness"],
    mentions: [],
    isReel: true,
    videoViews: 45000,
  },
  {
    id: "post-3",
    shortcode: "ghi789",
    caption:
      "My morning peptide stack that changed everything:\n\n- BPC-157 for gut health\n- TB-500 for recovery\n- CJC-1295 for growth hormone\n\nThis combination has been a game changer. What's your stack?\n\n#peptidestack #morningroutine #biohacking #health #wellness #peptidetherapy",
    mediaType: "IMAGE",
    mediaUrl: "",
    timestamp: "2026-03-10T08:00:00Z",
    likes: 890,
    comments: 67,
    engagementRate: 3.9,
    hashtags: ["#peptidestack", "#morningroutine", "#biohacking", "#health", "#wellness", "#peptidetherapy"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-4",
    shortcode: "jkl012",
    caption:
      "BREAKING: New research on Thymosin Alpha-1 shows incredible immune-boosting properties. Here's what the study found and why it matters for your health.\n\n#thymosin #immunehealth #peptideresearch #science #health",
    mediaType: "CAROUSEL",
    mediaUrl: "",
    timestamp: "2026-03-08T12:00:00Z",
    likes: 1800,
    comments: 134,
    engagementRate: 7.89,
    hashtags: ["#thymosin", "#immunehealth", "#peptideresearch", "#science", "#health"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-5",
    shortcode: "mno345",
    caption:
      "Day in my life as a peptide researcher. Lab work, reading studies, and creating content for you all.\n\n#dayinmylife #peptideresearch #science #behindthescenes",
    mediaType: "VIDEO",
    mediaUrl: "",
    timestamp: "2026-03-05T16:00:00Z",
    likes: 650,
    comments: 42,
    engagementRate: 2.82,
    hashtags: ["#dayinmylife", "#peptideresearch", "#science", "#behindthescenes"],
    mentions: [],
    isReel: true,
    videoViews: 18000,
  },
  {
    id: "post-6",
    shortcode: "pqr678",
    caption:
      "The truth about peptide sourcing. Not all peptides are created equal. Here's how to verify quality and purity.\n\nSave this post for reference!\n\n#peptidesafety #quality #biohacking #health #education",
    mediaType: "CAROUSEL",
    mediaUrl: "",
    timestamp: "2026-03-02T11:00:00Z",
    likes: 2400,
    comments: 201,
    engagementRate: 10.61,
    hashtags: ["#peptidesafety", "#quality", "#biohacking", "#health", "#education"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-7",
    shortcode: "stu901",
    caption:
      "Peptide myths debunked. Let's separate fact from fiction.\n\n#peptides #mythbusting #science #facts #health",
    mediaType: "VIDEO",
    mediaUrl: "",
    timestamp: "2026-02-28T09:00:00Z",
    likes: 3200,
    comments: 245,
    engagementRate: 14.06,
    hashtags: ["#peptides", "#mythbusting", "#science", "#facts", "#health"],
    mentions: [],
    isReel: true,
    videoViews: 72000,
  },
  {
    id: "post-8",
    shortcode: "vwx234",
    caption:
      "Quick tip: Store your reconstituted peptides at 2-8°C (36-46°F). Never freeze reconstituted peptides.\n\n#peptidetips #storage #health",
    mediaType: "IMAGE",
    mediaUrl: "",
    timestamp: "2026-02-25T13:00:00Z",
    likes: 420,
    comments: 28,
    engagementRate: 1.83,
    hashtags: ["#peptidetips", "#storage", "#health"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-9",
    shortcode: "yza567",
    caption:
      "GHK-Cu: The anti-aging peptide backed by 50+ studies. From skin regeneration to cognitive support, this peptide does it all.\n\nWould you try it? Let me know!\n\n#ghkcu #antiaging #skincare #peptides #biohacking #longevity #health",
    mediaType: "CAROUSEL",
    mediaUrl: "",
    timestamp: "2026-02-22T10:00:00Z",
    likes: 1650,
    comments: 112,
    engagementRate: 7.19,
    hashtags: ["#ghkcu", "#antiaging", "#skincare", "#peptides", "#biohacking", "#longevity", "#health"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-10",
    shortcode: "bcd890",
    caption:
      "Here's my complete guide to peptide reconstitution. Step by step for beginners.\n\n#peptides #howto #guide #beginners #health",
    mediaType: "VIDEO",
    mediaUrl: "",
    timestamp: "2026-02-18T15:00:00Z",
    likes: 1900,
    comments: 167,
    engagementRate: 8.44,
    hashtags: ["#peptides", "#howto", "#guide", "#beginners", "#health"],
    mentions: [],
    isReel: true,
    videoViews: 55000,
  },
  {
    id: "post-11",
    shortcode: "efg123",
    caption:
      "Collagen peptides vs injectable peptides - what's the difference and which is right for you?\n\n#collagen #peptides #skincare #health #comparison",
    mediaType: "CAROUSEL",
    mediaUrl: "",
    timestamp: "2026-02-15T11:30:00Z",
    likes: 980,
    comments: 73,
    engagementRate: 4.3,
    hashtags: ["#collagen", "#peptides", "#skincare", "#health", "#comparison"],
    mentions: [],
    isReel: false,
  },
  {
    id: "post-12",
    shortcode: "hij456",
    caption:
      "Just finished reviewing 3 new peptide studies. The research on Selank for anxiety is promising.\n\n#selank #anxiety #mentalhealth #peptideresearch #science",
    mediaType: "IMAGE",
    mediaUrl: "",
    timestamp: "2026-02-12T17:00:00Z",
    likes: 560,
    comments: 45,
    engagementRate: 2.47,
    hashtags: ["#selank", "#anxiety", "#mentalhealth", "#peptideresearch", "#science"],
    mentions: [],
    isReel: false,
  },
];

export const demoPosts: InstagramPost[] = basePosts;

export const demoBrandProfile: BrandProfile = {
  id: "demo-user",
  name: "Peptide Pro",
  username: "peptide_pro",
  colorPalette: ["#4263eb", "#364fc7", "#f8f9fa", "#212529", "#40c057"],
  toneOfVoice: ["educational", "professional", "storytelling", "casual"],
  contentPillars: ["peptide education", "research updates", "protocols", "myth busting", "personal journey"],
  targetAudience: "Health & Fitness Enthusiasts",
  niche: "Health & Wellness - Peptide Therapy",
  subNiches: ["biohacking", "peptidetherapy", "longevity", "wellness", "science"],
  brandKeywords: ["peptides", "biohacking", "health", "science", "research", "wellness", "optimization", "recovery", "healing"],
  avoidKeywords: ["guaranteed", "miracle", "cure"],
  postingStyle: {
    preferredFormats: ["CAROUSEL", "REEL", "IMAGE"],
    captionLength: "long",
    hashtagStrategy: "moderate",
    emojiUsage: "light",
    ctaStyle: "question",
  },
};

export const demoCompetitors: NicheCompetitor[] = [
  {
    profile: {
      id: "comp-1",
      username: "peptide_sciences",
      fullName: "Peptide Sciences",
      biography: "Premium peptide research. Education first.",
      profilePicUrl: "",
      followers: 45000,
      following: 320,
      postsCount: 580,
      isVerified: true,
    },
    posts: [],
    avgEngagementRate: 4.2,
    postingFrequency: 5,
    topContentTypes: [
      { type: "CAROUSEL", count: 180, avgEngagement: 5.1, percentage: 45 },
      { type: "REEL", count: 120, avgEngagement: 6.8, percentage: 30 },
    ],
    growthRate: 3.2,
    isOutlier: false,
    outlierScore: 0.5,
  },
  {
    profile: {
      id: "comp-2",
      username: "biohack_master",
      fullName: "Biohack Master",
      biography: "Optimizing human performance through science",
      profilePicUrl: "",
      followers: 89000,
      following: 450,
      postsCount: 920,
      isVerified: true,
    },
    posts: [],
    avgEngagementRate: 8.7,
    postingFrequency: 7,
    topContentTypes: [
      { type: "REEL", count: 400, avgEngagement: 11.2, percentage: 55 },
      { type: "CAROUSEL", count: 200, avgEngagement: 7.5, percentage: 25 },
    ],
    growthRate: 8.5,
    isOutlier: true,
    outlierScore: 2.3,
  },
  {
    profile: {
      id: "comp-3",
      username: "peptide_therapy_hub",
      fullName: "Peptide Therapy Hub",
      biography: "Evidence-based peptide therapy education",
      profilePicUrl: "",
      followers: 32000,
      following: 560,
      postsCount: 410,
      isVerified: false,
    },
    posts: [],
    avgEngagementRate: 3.8,
    postingFrequency: 4,
    topContentTypes: [
      { type: "IMAGE", count: 200, avgEngagement: 3.2, percentage: 50 },
      { type: "CAROUSEL", count: 120, avgEngagement: 4.8, percentage: 30 },
    ],
    growthRate: 1.5,
    isOutlier: false,
    outlierScore: -0.3,
  },
  {
    profile: {
      id: "comp-4",
      username: "longevity_labs",
      fullName: "Longevity Labs",
      biography: "Anti-aging science & peptide research",
      profilePicUrl: "",
      followers: 67000,
      following: 280,
      postsCount: 730,
      isVerified: true,
    },
    posts: [],
    avgEngagementRate: 6.5,
    postingFrequency: 6,
    topContentTypes: [
      { type: "CAROUSEL", count: 300, avgEngagement: 7.2, percentage: 40 },
      { type: "REEL", count: 250, avgEngagement: 8.1, percentage: 35 },
    ],
    growthRate: 5.1,
    isOutlier: true,
    outlierScore: 1.7,
  },
];

export const demoTrends: NicheTrend[] = [
  {
    id: "trend-1",
    topic: "#tirzepatide",
    trendScore: 92,
    velocity: 2.4,
    volume: 45,
    relatedHashtags: ["#glp1", "#weightloss", "#peptides", "#obesity", "#health"],
    topPosts: [],
    nicheRelevance: 85,
    saturation: 32,
  },
  {
    id: "trend-2",
    topic: "#bpc157",
    trendScore: 78,
    velocity: 1.5,
    volume: 120,
    relatedHashtags: ["#healing", "#guthealth", "#peptidetherapy", "#recovery"],
    topPosts: [],
    nicheRelevance: 95,
    saturation: 65,
  },
  {
    id: "trend-3",
    topic: "#nad+",
    trendScore: 85,
    velocity: 1.8,
    volume: 67,
    relatedHashtags: ["#longevity", "#antiaging", "#biohacking", "#mitochondria"],
    topPosts: [],
    nicheRelevance: 72,
    saturation: 28,
  },
  {
    id: "trend-4",
    topic: "#peptidestack",
    trendScore: 71,
    velocity: 1.2,
    volume: 34,
    relatedHashtags: ["#biohacking", "#optimization", "#health", "#peptides"],
    topPosts: [],
    nicheRelevance: 98,
    saturation: 41,
  },
  {
    id: "trend-5",
    topic: "#rapamycin",
    trendScore: 68,
    velocity: 1.6,
    volume: 28,
    relatedHashtags: ["#longevity", "#mtor", "#antiaging", "#science"],
    topPosts: [],
    nicheRelevance: 65,
    saturation: 18,
  },
];

export const demoSuggestions: ContentSuggestion[] = [
  {
    id: "sug-1",
    title: "Trending: Tirzepatide Deep Dive",
    description: "Capitalize on the trending topic #tirzepatide which has a trend score of 92 and is growing 240% faster than baseline.",
    contentType: "CAROUSEL",
    suggestedCaption:
      "Tirzepatide: Everything you need to know about the hottest peptide in 2026.\n\nThis dual GIP/GLP-1 receptor agonist is making waves in weight management and metabolic health.\n\nSwipe through for:\n- How it works\n- Key clinical results\n- Who it's for\n- Side effects to watch\n- How it compares to semaglutide\n\nWhat questions do you have about tirzepatide? Drop them below!\n\n#tirzepatide #glp1 #peptides #weightloss #metabolichealth #biohacking #health",
    suggestedHashtags: ["#tirzepatide", "#glp1", "#peptides", "#weightloss", "#metabolichealth", "#biohacking", "#health"],
    bestTimeToPost: "Wednesday at 10:00",
    estimatedEngagement: 8.5,
    inspirationSource: "Trending topic with 45 recent uses",
    trendScore: 92,
    brandAlignmentScore: 88,
    contentPillar: "peptide education",
    status: "suggested",
    reasoning: "Tirzepatide is the #1 trending topic in your niche. Low saturation (32%) means there's room to stand out with educational content.",
  },
  {
    id: "sug-2",
    title: "Replicate Success: Myth-Busting Reel",
    description: "Create content similar to your top-performing REEL that achieved 14.06% engagement.",
    contentType: "REEL",
    suggestedCaption:
      "3 peptide myths that need to die in 2026.\n\nMyth 1: All peptides are the same\nMyth 2: More is always better\nMyth 3: You don't need bloodwork\n\nThe truth? Science always wins. Which myth surprised you most?\n\n#peptides #mythbusting #science #health #biohacking",
    suggestedHashtags: ["#peptides", "#mythbusting", "#science", "#health", "#biohacking", "#peptidetherapy"],
    bestTimeToPost: "Thursday at 14:00",
    estimatedEngagement: 11.2,
    inspirationSource: "Your top post (stu901)",
    trendScore: 75,
    brandAlignmentScore: 95,
    contentPillar: "myth busting",
    status: "suggested",
    reasoning: "Your myth-busting reel got 14.06% engagement - 2.3x your average. Reels with contrarian hooks consistently outperform for your account.",
  },
  {
    id: "sug-3",
    title: "NAD+ & Longevity Connection",
    description: "Capitalize on the trending NAD+ topic with educational carousel content.",
    contentType: "CAROUSEL",
    suggestedCaption:
      "NAD+ peptides: The longevity game changer backed by science.\n\nNAD+ levels decline 50% by age 60. Here's why peptide-based NAD+ support could be the key to healthy aging.\n\nSlide 1: What is NAD+?\nSlide 2: Why levels decline\nSlide 3: NAD+ boosting peptides\nSlide 4: The research\nSlide 5: Protocol considerations\n\nSave this for your longevity toolkit!\n\n#nad #longevity #antiaging #biohacking #peptides #health #science",
    suggestedHashtags: ["#nad", "#longevity", "#antiaging", "#biohacking", "#peptides", "#mitochondria"],
    bestTimeToPost: "Tuesday at 11:00",
    estimatedEngagement: 7.8,
    inspirationSource: "Trending topic + competitor analysis",
    trendScore: 85,
    brandAlignmentScore: 82,
    contentPillar: "research updates",
    status: "suggested",
    reasoning: "NAD+ is trending (score: 85) with low saturation (28%). @longevity_labs gets 7.2% avg engagement on similar carousel content.",
  },
  {
    id: "sug-4",
    title: "Niche Outlier: Biohack Master's Reel Style",
    description: "Inspired by @biohack_master's high-performing reel format.",
    contentType: "REEL",
    suggestedCaption:
      "POV: You just discovered peptides can help with [specific condition].\n\nThe research is clear. Here's what the science says.\n\n[Educational hook + 3 key points + CTA]\n\nFollow for more science-backed peptide content.\n\n#peptides #biohacking #health #science",
    suggestedHashtags: ["#peptides", "#biohacking", "#health", "#science", "#pov", "#peptidetherapy"],
    bestTimeToPost: "Friday at 12:00",
    estimatedEngagement: 9.5,
    inspirationSource: "@biohack_master (niche outlier)",
    trendScore: 80,
    brandAlignmentScore: 78,
    contentPillar: "peptide education",
    status: "suggested",
    reasoning: "@biohack_master's POV-style reels get 11.2% engagement. Adapting this format to your educational brand voice could boost reel performance by 60%.",
  },
  {
    id: "sug-5",
    title: "Peptide Sourcing Safety Guide",
    description: "Replicate your top carousel about peptide quality (10.61% engagement).",
    contentType: "CAROUSEL",
    suggestedCaption:
      "Updated for 2026: How to verify your peptide source.\n\n5 red flags to watch for:\n1. No third-party testing\n2. No COA available\n3. Suspiciously low prices\n4. No customer support\n5. Vague ingredient labels\n\nYour health is worth the extra verification. What would you add to this list?\n\n#peptidesafety #quality #biohacking #health #peptides",
    suggestedHashtags: ["#peptidesafety", "#quality", "#biohacking", "#health", "#peptides", "#purity"],
    bestTimeToPost: "Monday at 10:00",
    estimatedEngagement: 8.9,
    inspirationSource: "Your top post (pqr678)",
    trendScore: 55,
    brandAlignmentScore: 96,
    contentPillar: "peptide education",
    status: "scheduled",
    scheduledDate: "2026-03-23",
    scheduledTime: "10:00",
    reasoning: "Your safety/quality content gets 10.61% engagement - your highest. This updated version leverages the same trust-building format.",
  },
  {
    id: "sug-6",
    title: "Weekly Research Roundup",
    description: "Create a recurring series covering the latest peptide research papers.",
    contentType: "CAROUSEL",
    suggestedCaption:
      "This week in peptide research:\n\n1. New BPC-157 gut microbiome study\n2. Selank anxiety trial results\n3. GHK-Cu skin regeneration findings\n\nWhich study interests you most? I'll do a deep dive on the winner!\n\n#peptideresearch #science #research #peptides #health",
    suggestedHashtags: ["#peptideresearch", "#science", "#research", "#peptides", "#weeklyroundup"],
    bestTimeToPost: "Sunday at 10:00",
    estimatedEngagement: 6.5,
    inspirationSource: "Content gap analysis",
    trendScore: 60,
    brandAlignmentScore: 92,
    contentPillar: "research updates",
    status: "suggested",
    reasoning: "A recurring series builds audience habit and expectation. Your research content gets above-average engagement and establishes authority.",
  },
];

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "cal-1",
    date: "2026-03-20",
    time: "10:00",
    suggestion: demoSuggestions[0],
    status: "scheduled",
    notes: "Use latest clinical data from March 2026 study",
  },
  {
    id: "cal-2",
    date: "2026-03-22",
    time: "14:00",
    suggestion: demoSuggestions[1],
    status: "scheduled",
  },
  {
    id: "cal-3",
    date: "2026-03-23",
    time: "10:00",
    suggestion: demoSuggestions[4],
    status: "scheduled",
  },
  {
    id: "cal-4",
    date: "2026-03-25",
    time: "11:00",
    suggestion: demoSuggestions[2],
    status: "draft",
  },
  {
    id: "cal-5",
    date: "2026-03-27",
    time: "12:00",
    suggestion: demoSuggestions[3],
    status: "draft",
  },
  {
    id: "cal-6",
    date: "2026-03-29",
    time: "10:00",
    suggestion: demoSuggestions[5],
    status: "draft",
  },
];

export const demoAnalytics: AnalyticsData = {
  totalPosts: 12,
  avgEngagementRate: 6.52,
  bestPostingTimes: [
    { day: "Wednesday", hour: 10, engagement: 9.21 },
    { day: "Thursday", hour: 14, engagement: 8.44 },
    { day: "Tuesday", hour: 11, engagement: 7.89 },
    { day: "Monday", hour: 10, engagement: 7.19 },
    { day: "Friday", hour: 12, engagement: 5.47 },
  ],
  topPerformingPosts: [basePosts[6], basePosts[5], basePosts[1], basePosts[9], basePosts[3]],
  worstPerformingPosts: [basePosts[7], basePosts[11], basePosts[4], basePosts[2], basePosts[10]],
  contentTypePerformance: [
    { type: "REEL", count: 4, avgEngagement: 8.63, percentage: 33 },
    { type: "CAROUSEL", count: 5, avgEngagement: 7.09, percentage: 42 },
    { type: "IMAGE", count: 3, avgEngagement: 2.73, percentage: 25 },
  ],
  hashtagPerformance: [
    { hashtag: "#peptides", avgEngagement: 7.85, uses: 8 },
    { hashtag: "#biohacking", avgEngagement: 7.24, uses: 6 },
    { hashtag: "#health", avgEngagement: 6.42, uses: 10 },
    { hashtag: "#science", avgEngagement: 7.98, uses: 5 },
    { hashtag: "#peptidetherapy", avgEngagement: 5.79, uses: 3 },
    { hashtag: "#wellness", avgEngagement: 5.12, uses: 4 },
    { hashtag: "#mythbusting", avgEngagement: 14.06, uses: 1 },
    { hashtag: "#longevity", avgEngagement: 7.19, uses: 1 },
  ],
  growthMetrics: [
    { date: "2026-02-10", followers: 22000, engagement: 3.4 },
    { date: "2026-02-17", followers: 22500, engagement: 5.14 },
    { date: "2026-02-24", followers: 23100, engagement: 7.95 },
    { date: "2026-03-03", followers: 23600, engagement: 6.72 },
    { date: "2026-03-10", followers: 24100, engagement: 5.39 },
    { date: "2026-03-17", followers: 24500, engagement: 7.34 },
  ],
  insights: [
    {
      id: "insight-1",
      type: "trend",
      title: "Engagement Trending Up",
      description: "Your recent posts are getting 18% more engagement than your average.",
      metric: "engagementRate",
      value: 7.69,
      change: 18,
      recommendation: "Your myth-busting and educational carousel content is resonating. Double down on these formats.",
      relatedPosts: ["post-1", "post-2", "post-4"],
    },
    {
      id: "insight-2",
      type: "opportunity",
      title: "Underutilized REEL Format",
      description: "REELs get 32% more engagement than average but only make up 33% of your content.",
      metric: "contentType",
      value: 8.63,
      change: 0.32,
      recommendation: "Increase REEL content from 33% to at least 45% of your posts for maximum reach.",
      relatedPosts: ["post-2", "post-5", "post-7", "post-10"],
    },
    {
      id: "insight-3",
      type: "anomaly",
      title: "Static Images Underperforming",
      description: "IMAGE posts get 58% less engagement than your average. Consider using carousels instead.",
      metric: "contentType",
      value: 2.73,
      change: -0.58,
      recommendation: "Convert single image ideas into carousel posts or short reels for better performance.",
      relatedPosts: ["post-3", "post-8", "post-12"],
    },
  ],
};
